CREATE DATABASE IF NOT EXISTS EMPRESA_COCHES;

USE EMPRESA_COCHES;

/*********************************************************/

CREATE TABLE IF NOT EXISTS EXPOSICIONES
(
    IDEXPOSICION INT(5) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(45) NOT NULL,
    LUGAR VARCHAR(30) NOT NULL,

    PRIMARY KEY (IDEXPOSICION)
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE IF NOT EXISTS PROVEEDORES
(
    IDPROVEEDOR INT(5) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(45) NOT NULL,
    FECHAALTA DATE,

    PRIMARY KEY(IDPROVEEDOR)
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE IF NOT EXISTS VENDEDORES
(
    DNI CHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30) NOT NULL,
    MOVIL CHAR(9) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    FECHAALTA DATE,

    PRIMARY KEY(DNI)
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE VENDEDORESASALARIADOS
(
    DNI CHAR(9) NOT NULL, /****PK REFERENCES PK VENDEDORES: VENDEDORESASALARIADOS IS VENDEDORES****/
    SALARIO DOUBLE NOT NULL,

    PRIMARY KEY(DNI),

    CONSTRAINT FK1_VENDEDOR
        FOREIGN KEY (DNI)
            REFERENCES VENDEDORES(DNI)
                ON DELETE CASCADE
                ON UPDATE CASCADE,
    INDEX FK1_VENDEDOR(DNI)
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE VENDEDORESCOMISION
(
    DNI CHAR(9) NOT NULL,   /****PK REFERENCES PK VENDEDORES: VENDEDORESCOMISION IS VENDEDORES****/
    COMISION DOUBLE NOT NULL,

    PRIMARY KEY(DNI),
    
    CONSTRAINT FK2_VENDEDOR
        FOREIGN KEY (DNI)
            REFERENCES VENDEDORES(DNI)
                ON DELETE CASCADE
                ON UPDATE CASCADE,
    INDEX FK2_VENDEDOR(DNI)
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE IF NOT EXISTS CLIENTES
(
    DNI CHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30) NOT NULL,
    MOVIL CHAR(9) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    FECHAALTA DATE,

    PRIMARY KEY(DNI)
)
ENGINE INNODB;


CREATE TABLE IF NOT EXISTS REPARACIONES
(
    IDREPARACION INT(5) NOT NULL AUTO_INCREMENT,
    FECHAREPARACION DATE NOT NULL,
    DESCRIPCION VARCHAR(100),
    TALLER INT(5) NOT NULL AUTO_INCREMENT, /**FK CLAVE TALLER, REL REALIZAR REPARACION, OBLIGATORIA**/
    COCHE INT(5) NOT NULL AUTO_INCREMENT,  /**FK CLAVE COCHE, REL SER REPARADO, OBLIGATORIA**/
    
    PRIMARY KEY(IDREPARACION),
    
    CONSTRAINT FK3_TALLER
        FOREIGN KEY(TALLER)
            REFERENCES TALLERES(IDTALLER)
                ON DELETE CASCADE
                ON UPDATE CASCADE,
    INDEX FK3_TALLER(TALLER),
    
    CONSTRAINT FK4_COCHE
        FOREIGN KEY(COCHE)
            REFERENCES COCHES(IDCOCHE)
                ON DELETE CASCADE 
                ON UPDATE CASCADE,
    INDEX FK4_COCHE(COCHE)
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE IF NOT EXISTS REPARACIONESELECTRICAS
(
    IDREPARACION INT(5) NOT NULL AUTO_INCREMENT,
    COMPONENTE VARCHAR(45) NOT NULL,
    PRIMARY KEY(IDREPARACION)
    INDEX FK_REPARACION(IDREPARACION),
    CONSTRAINT FK_REPARACION
    FOREIGN KEY (IDREPARACION)
    REFERENCES REPARACIONES(IDREPARACION)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE IF NOT EXISTS REPARACIONESCHAPA
(
    IDREPARACION INT(5) NOT NULL AUTO_INCREMENT,
    COLORCHAPA VARCHAR(45) NOT NULL,
    PRIMARY KEY(IDREPARACION)
    INDEX FK2_REPARACION(IDREPARACION),
    CONSTRAINT FK2_REPARACION
    FOREIGN KEY (IDREPARACION)
    REFERENCES REPARACIONES(IDREPARACION)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE IF NOT EXISTS REPARACIONESMECANICAS
(
    IDREPARACION INT(5) NOT NULL AUTO_INCREMENT,
    PARTE VARCHAR(45) NOT NULL,
    PRIMARY KEY(IDREPARACION)
    INDEX FK3_REPARACION(IDREPARACION),
    CONSTRAINT FK3_REPARACION
    FOREIGN KEY (IDREPARACION)
    REFERENCES REPARACIONES(IDREPARACION)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE IF NOT EXISTS TALLERES
(
    IDTALLER INT(5) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    PRIMARY KEY(IDTALLER)
)
ENGINE INNODB;

/*********************************************************/

CREATE TABLE IF NOT EXISTS COCHES
(
    IDCOCHE INT(5) NOT NULL AUTO_INCREMENT,
    MARCA VARCHAR(30) NOT NULL,
    MODELO VARCHAR(30) NOT NULL,
    MATRICULA CHAR(7) NOT NULL,
    TIPO ENUM('TURISMO','INDUSTRIAL','TODOTERRENO') NOT NULL,
    PRECIOCOMPRA DOUBLE NOT NULL,
    PRECIOVENTA DOUBLE NOT NULL,
    REPARADO BOOLEAN NOT NULL,
    FECHAALTA DATE,
    FECHAVENTA DATE,
    PROVEEDOR INT(5) NOT NULL AUTO_INCREMENT,
    EXPOSICION INT(5) NOT NULL AUTO_INCREMENT,
    VENDEDOR CHAR(9) NOT NULL,
    CLIENTE CHAR(9) NOT NULL,
    PRIMARY KEY(IDCOCHE),
    INDEX FK_PROVEEDOR(PROVEEDOR),
    INDEX FK_EXPOSICION(EXPOSICION),
    INDEX FK_CLIENTE(CLIENTE),
    INDEX FK3_VENDEDOR(VENDEDOR),
    CONSTRAINT FK_PROVEEDOR
    FOREIGN KEY(PROVEEDOR)
    REFERENCES PROVEEDORES(IDPROVEEDOR)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_EXPOSICION
    FOREIGN KEY(EXPOSICION)
    REFERENCES EXPOSICIONES(IDEXPOSICION)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_CLIENTE
    FOREIGN KEY(CLIENTE)
    REFERENCES CLIENTES(DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK3_VENDEDOR
    FOREIGN KEY(VENDEDOR)
    REFERENCES VENDEDORES(DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE INNODB;
