CREATE TABLE IF NOT EXISTS EXPOSICIONES(
IDEXPOSICION INT(5) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
LUGAR VARCHAR(30) NOT NULL,
PRIMARY KEY (IDEXPOSICION))

CREATE TABLE IF NOT EXISTS PROVEEDORES(
IDPROVEEDOR INT(5) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
FECHAALTA DATE,
PRIMARY KEY(IDPROVEEDOR))


CREATE TABLE IF NOT EXISTS VENDEDORES(
DNI CHAR(9) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO1 VARCHAR(30) NOT NULL,
APELLIDO2 VARCHAR(30) NOT NULL,
MOVIL CHAR(9) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
FECHAALTA DATE,
PRIMARY KEY(DNI))

CREATE TABLE VENDEDORESASALARIADOS(
DNI CHAR(9) NOT NULL,
SALARIO DOUBLE NOT NULL,
PRIMARY KEY(DNI),
INDEX FK_VENDEDOR(DNI),
CONSTRAINT FK_VENDEDOR
FOREIGN KEY (DNI)
REFERENCES VENDEDORES(DNI)
ON DELETE CASCADE
ON UPDATE CASCADE)

CREATE TABLE VENDEDORESCOMISION(
DNI CHAR(9) NOT NULL,
COMISION DOUBLE NOT NULL,
PRIMARY KEY(DNI),
INDEX FK2_VENDEDOR(DNI),
CONSTRAINT FK2_VENDEDOR
FOREIGN KEY (DNI)
REFERENCES VENDEDORES(DNI)
ON DELETE CASCADE
ON UPDATE CASCADE)


CREATE TABLE IF NOT EXISTS CLIENTES(
DNI CHAR(9) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO1 VARCHAR(30) NOT NULL,
APELLIDO2 VARCHAR(30) NOT NULL,
MOVIL CHAR(9) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
FECHAALTA DATE,
PRIMARY KEY(DNI))
)


CREATE TABLE IF NOT EXISTS REPARACIONES(
IDREPARACION INT(5) NOT NULL AUTO_INCREMENT,
FECHAREPARACION DATE NOT NULL,
DESCRIPCION VARCHAR(100),
TALLER INT(5) NOT NULL AUTO_INCREMENT,
COCHE INT(5) NOT NULL AUTO_INCREMENT,
PRIMARY KEY(IDREPARACION),
INDEX FK_TALLER(TALLER),
INDEX FK_COCHE(COCHE),
CONSTRAINT FK_TALLER
FOREIGN KEY(TALLER)
REFERENCES TALLERES(IDTALLER)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_COCHE
FOREIGN KEY(COCHE)
REFERENCES COCHES(IDCOCHE)
ON DELETE CASCADE 
ON UPDATE CASCADE
 
)

CREATE TABLE IF NOT EXISTS REPARACIONESELECTRICAS(
IDREPARACION INT(5) NOT NULL AUTO_INCREMENT,
COMPONENTE VARCHAR(45) NOT NULL,
PRIMARY KEY(IDREPARACION)
INDEX FK_REPARACION(IDREPARACION),
CONSTRAINT FK_REPARACION
FOREIGN KEY (IDREPARACION)
REFERENCES REPARACIONES(IDREPARACION)
ON DELETE CASCADE
ON UPDATE CASCADE)

CREATE TABLE IF NOT EXISTS REPARACIONESCHAPA(
IDREPARACION INT(5) NOT NULL AUTO_INCREMENT,
COLORCHAPA VARCHAR(45) NOT NULL,
PRIMARY KEY(IDREPARACION)
INDEX FK2_REPARACION(IDREPARACION),
CONSTRAINT FK2_REPARACION
FOREIGN KEY (IDREPARACION)
REFERENCES REPARACIONES(IDREPARACION)
ON DELETE CASCADE
ON UPDATE CASCADE)


CREATE TABLE IF NOT EXISTS REPARACIONESMECANICAS(
IDREPARACION INT(5) NOT NULL AUTO_INCREMENT,
PARTE VARCHAR(45) NOT NULL,
PRIMARY KEY(IDREPARACION)
INDEX FK3_REPARACION(IDREPARACION),
CONSTRAINT FK3_REPARACION
FOREIGN KEY (IDREPARACION)
REFERENCES REPARACIONES(IDREPARACION)
ON DELETE CASCADE
ON UPDATE CASCADE)





CREATE TABLE IF NOT EXISTS TALLERES(
IDTALLER INT(5) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(30) NOT NULL,
PRIMARY KEY(IDTALLER))







CREATE TABLE IF NOT EXISTS COCHES(
IDCOCHE INT(5) NOT NULL AUTO_INCREMENT,
MARCA VARCHAR(30) NOT NULL,
MODELO VARCHAR(30) NOT NULL,
MATRICULA CHAR(7) NOT NULL,
TIPO ENUM('','','') NOT NULL,
PRECIOCOMPRA DOUBLE NOT NULL,
PRECIOVENTA DOUBLE NOT NULL,
REPARADO BOOLEAN NOT NULL,
FECHAALTA DATE,
FECHAVENTA DATE,
PROVEEDOR INT(5) NOT NULL AUTO_INCREMENT,
EXPOSICION INT(5) NOT NULL AUTO_INCREMENT,
VENDEDOR CHAR(9) NOT NULL,
CLIENTE CHAR(9) NOT NULL,
PRIMARY KEY(IDCOCHE),
INDEX FK_PROVEEDOR(PROVEEDOR),
INDEX FK_EXPOSICION(EXPOSICION),
INDEX FK_CLIENTE(CLIENTE),
INDEX FK3_VENDEDOR(VENDEDOR),
CONSTRAINT FK_PROVEEDOR
FOREIGN KEY(PROVEEDOR)
REFERENCES PROVEEDORES(IDPROVEEDOR)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_EXPOSICION
FOREING KEY(EXPOSICION)
REFERENCES EXPOSICIONES(IDEXPOSICION)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_CLIENTE
FOREING KEY(CLIENTE)
REFERENCES CLIENTES(DNI)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK3_VENDEDOR
FOREING KEY(VENDEDOR)
REFERENCES VENDEDORES(DNI)
ON DELETE CASCADE
ON UPDATE CASCADE
)









)
